/*
Copyright The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/tmax-cloud/cluster-manager-operator/api/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	scheme "k8s.io/client-go/kubernetes/scheme"
	rest "k8s.io/client-go/rest"
)

// ClusterManagerGetter has a method to return a ClusterManagerInterface.
// A group's client should implement this interface.
type ClusterManagerGetter interface {
	ClusterManagers(namespace string) ClusterManagerInterface
}

// ClusterManagerInterface has methods to work with clusterManager resources.
type ClusterManagerInterface interface {
	Create(ctx context.Context, clusterManager *v1alpha1.ClusterManager, opts metav1.CreateOptions) (*v1alpha1.ClusterManager, error)
	Update(ctx context.Context, clusterManager *v1alpha1.ClusterManager, opts metav1.UpdateOptions) (*v1alpha1.ClusterManager, error)
	UpdateStatus(ctx context.Context, clusterManager *v1alpha1.ClusterManager, opts metav1.UpdateOptions) (*v1alpha1.ClusterManager, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1alpha1.ClusterManager, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1alpha1.ClusterManagerList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterManager, err error)
	clusterManagerExpansion
}

// clusterManagers implements ClusterManagerInterface
type clusterManagers struct {
	client rest.Interface
	ns     string
}

// newClusterManagers returns a clusterManagers
func newClusterManagers(c *ClusterV1alpha1Client, namespace string) *clusterManagers {
	return &clusterManagers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterManager, and returns the corresponding clusterManager object, and an error if there is any.
func (c *clusterManagers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1alpha1.ClusterManager, err error) {
	result = &v1alpha1.ClusterManager{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterManagers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of clusterManagers that match those selectors.
func (c *clusterManagers) List(ctx context.Context, opts metav1.ListOptions) (result *v1alpha1.ClusterManagerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterManagerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterManagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterManagers.
func (c *clusterManagers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterManagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterManager and creates it.  Returns the server's representation of the clusterManager, and an error, if there is any.
func (c *clusterManagers) Create(ctx context.Context, clusterManager *v1alpha1.ClusterManager, opts metav1.CreateOptions) (result *v1alpha1.ClusterManager, err error) {
	result = &v1alpha1.ClusterManager{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterManagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterManager).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterManager and updates it. Returns the server's representation of the clusterManager, and an error, if there is any.
func (c *clusterManagers) Update(ctx context.Context, clusterManager *v1alpha1.ClusterManager, opts metav1.UpdateOptions) (result *v1alpha1.ClusterManager, err error) {
	result = &v1alpha1.ClusterManager{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterManagers").
		Name(clusterManager.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterManager).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterManagers) UpdateStatus(ctx context.Context, clusterManager *v1alpha1.ClusterManager, opts metav1.UpdateOptions) (result *v1alpha1.ClusterManager, err error) {
	result = &v1alpha1.ClusterManager{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterManagers").
		Name(clusterManager.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterManager).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterManager and deletes it. Returns an error if one occurs.
func (c *clusterManagers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterManagers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterManagers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterManagers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterManager.
func (c *clusterManagers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterManager, err error) {
	result = &v1alpha1.ClusterManager{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterManagers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
